apiVersion: v1
kind: Service
metadata:
  name: deepstream
  namespace: aams
  labels:
    app: deepstream
    component: video-analytics
  annotations:
    service.beta.kubernetes.io/description: "DeepStream video analytics pipeline service for real-time processing"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: rtsp
      port: 8554
      targetPort: 8554
      protocol: TCP
  selector:
    app: deepstream
    component: video-analytics
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  publishNotReadyAddresses: false
  internalTrafficPolicy: Cluster