# Kubernetes Secrets configuration for Agricultural Management System
# Version: 1.0.0
# Contains sensitive credentials and encryption keys - handle with care

---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: agricultural-system
  labels:
    app.kubernetes.io/name: database-credentials
    app.kubernetes.io/part-of: autonomous-agricultural-management
    security.agricultural.io/type: database
    security.agricultural.io/rotation-period: 30d
  annotations:
    security.agricultural.io/last-rotated: "2024-02-20T00:00:00Z"
    security.agricultural.io/encryption: aes-256-gcm
type: Opaque
data:
  TIMESCALEDB_USERNAME: YWdyaWN1bHR1cmFsX2RiX3VzZXI=  # agricultural_db_user
  TIMESCALEDB_PASSWORD: VDNzdCFuZ0AxMjM0NTY3ODk=  # Complex password
  MINIO_ACCESS_KEY: YWdyaWN1bHR1cmFsX21pbmlvX2FjY2Vzcw==  # agricultural_minio_access
  MINIO_SECRET_KEY: TWluaW9AMTIzNDU2Nzg5QCM=  # Complex key
  REDIS_PASSWORD: UmVkaXNAMTIzNDU2Nzg5QCM=  # Complex password
  POSTGRES_REPLICATION_PASSWORD: UmVwbGljYXRpb25AMTIzNDU2Nzg5  # Complex password

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: agricultural-system
  labels:
    app.kubernetes.io/name: auth-secrets
    app.kubernetes.io/part-of: autonomous-agricultural-management
    security.agricultural.io/type: authentication
    security.agricultural.io/rotation-period: 90d
  annotations:
    security.agricultural.io/last-rotated: "2024-02-20T00:00:00Z"
    security.agricultural.io/compliance: gdpr,iso27001
type: Opaque
data:
  JWT_SECRET_KEY: SkpXVF9TM2NyZXRAMTIzNDU2Nzg5QCM=  # Complex JWT key
  OAUTH_CLIENT_ID: YWdyaWN1bHR1cmFsX2NsaWVudA==  # agricultural_client
  OAUTH_CLIENT_SECRET: T0F1dGhAMTIzNDU2Nzg5QCM=  # Complex OAuth secret
  KEYCLOAK_ADMIN_PASSWORD: S2V5Y2xvYWtAMTIzNDU2Nzg5QCM=  # Complex admin password
  MFA_SEED_KEY: TUZAX1MyZWRAMTIzNDU2Nzg5QCM=  # Complex MFA seed
  API_GATEWAY_KEY: QVBJQDEyMzQ1Njc4OUAj  # Complex API key

---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
  namespace: agricultural-system
  labels:
    app.kubernetes.io/name: encryption-keys
    app.kubernetes.io/part-of: autonomous-agricultural-management
    security.agricultural.io/type: encryption
    security.agricultural.io/rotation-period: 180d
  annotations:
    security.agricultural.io/last-rotated: "2024-02-20T00:00:00Z"
    security.agricultural.io/key-type: aes-256-gcm,rsa-4096
type: Opaque
data:
  AES_KEY: QUVTXzI1Nl9HQ01fS0VZQDEyMzQ1Njc4OUAj  # AES-256 key
  TLS_PRIVATE_KEY: VExTX1BSSVZBVEVfS0VZQDEyMzQ1Njc4OUAj  # TLS private key
  TLS_CERTIFICATE: VExTX0NFUlRJRklDQVRFQDEyMzQ1Njc4OUAj  # TLS certificate
  TLS_CA_CERTIFICATE: VExTX0NBX0NFUlRJRklDQVRFQDEyMzQ1Njc4OUAj  # CA certificate
  SIGNING_KEY: U0lHTklOR19LRVlAMTIzNDU2Nzg5QCM=  # Signing key
  MASTER_KEY: TUFTVEVSX0tFWUAxMjM0NTY3ODlAIw==  # Master encryption key