apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: agricultural-system
  labels:
    app: jaeger
    component: monitoring
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: autonomous-agricultural-management
    app.kubernetes.io/component: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14268"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.41.0 # version: 1.41.0
        ports:
        - name: ui
          containerPort: 16686
          protocol: TCP
        - name: jg-compact-trft
          containerPort: 6831
          protocol: UDP
        - name: jg-binary-trft
          containerPort: 6832
          protocol: UDP
        - name: config-rest
          containerPort: 5778
          protocol: TCP
        - name: grpc
          containerPort: 14250
          protocol: TCP
        - name: collector-http
          containerPort: 14268
          protocol: TCP
        - name: zipkin
          containerPort: 9411
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 512Mi
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: MEMORY_MAX_TRACES
          value: "50000"
        - name: SPAN_STORAGE_TYPE
          value: "memory"
        - name: SAMPLING_STRATEGIES_FILE
          value: "/etc/jaeger/sampling/sampling.json"
        - name: METRICS_STORAGE_TYPE
          value: "prometheus"
        readinessProbe:
          httpGet:
            path: /
            port: 14268
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 14268
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - name: sampling-config
          mountPath: /etc/jaeger/sampling
          readOnly: true
      volumes:
      - name: sampling-config
        configMap:
          name: jaeger-sampling-config
          defaultMode: 0440