apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: agricultural-system
  labels:
    app: jaeger
    component: monitoring
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: autonomous-agricultural-management
    app.kubernetes.io/component: tracing
    security.agricultural.io/zone: protected
    monitoring.agricultural.io/latency-tracked: "true"
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
      protocol: TCP
    - name: jg-compact-trft
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: jg-binary-trft
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: config-rest
      port: 5778
      targetPort: 5778
      protocol: TCP
    - name: grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
    - name: collector-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
  type: ClusterIP