apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-data
  namespace: agricultural-system
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/part-of: autonomous-agricultural-management
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
  annotations:
    # Storage provisioner annotations for local NVMe storage
    storage.kubernetes.io/storage-provisioner: kubernetes.io/local-storage
    volume.kubernetes.io/storage-class: fast-local-storage
    volume.beta.kubernetes.io/storage-class: fast-local-storage
    # Performance optimization annotations
    volume.kubernetes.io/selected-node: ""  # Will be set by scheduler
    volume.kubernetes.io/mount-options: "noatime,nodiratime,discard"
    # Backup and maintenance annotations
    backup.velero.io/backup-volumes: timescaledb-data
    maintenance.velero.io/backup-schedule: "0 1 * * *"
spec:
  accessModes:
    - ReadWriteOnce  # Single node access for data consistency
  storageClassName: fast-local-storage  # Using NVMe storage class
  resources:
    requests:
      storage: 500Gi  # Allocated storage as per requirements
    limits:
      storage: 500Gi  # Matching request to prevent overallocation
  selector:
    matchLabels:
      storage.kubernetes.io/type: nvme