apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: security
  labels:
    app: vault
    component: security
    part-of: security-infrastructure
    managed-by: kubernetes
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
    security.agricultural.io/encryption: "enabled"
    security.agricultural.io/internal-only: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8200"
    prometheus.io/path: "/v1/sys/metrics"
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8200
      targetPort: api-port
      protocol: TCP
      appProtocol: https
    - name: cluster
      port: 8201
      targetPort: cluster-port
      protocol: TCP
      appProtocol: https
  selector:
    app: vault
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  publishNotReadyAddresses: false
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6