apiVersion: v1
kind: Service
metadata:
  name: tao-toolkit
  namespace: agricultural-system
  labels:
    app.kubernetes.io/name: tao-toolkit
    app.kubernetes.io/part-of: autonomous-agricultural-management
    app.kubernetes.io/version: "4.0.0"
    app.kubernetes.io/component: ai-inference
    monitoring.agricultural-system.io/scrape: "true"
    monitoring.agricultural-system.io/port: "8001"
  annotations:
    networking.agricultural-system.io/allowed-ingress: "deepstream-pipeline"
    security.agricultural-system.io/tls-required: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    service.agricultural-system.io/latency-sla: "100ms"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: inference
      appProtocol: https
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: metrics
      appProtocol: http
  selector:
    app.kubernetes.io/name: tao-toolkit
    app.kubernetes.io/version: "4.0.0"
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800