apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: agricultural-system
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: autonomous-agricultural-management
    app.kubernetes.io/component: identity-provider
data:
  # Core Settings
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_PROXY: "edge"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "true"
  KC_HTTP_RELATIVE_PATH: "/auth"

  # Database Configuration
  KC_DB: "postgres"
  KC_DB_URL_HOST: "timescaledb.agricultural-system.svc.cluster.local"
  KC_DB_URL_PORT: "5432"
  KC_DB_URL_DATABASE: "keycloak"
  KC_DB_USERNAME: "${KEYCLOAK_DB_USER}"
  KC_DB_PASSWORD: "${KEYCLOAK_DB_PASSWORD}"

  # Security Settings
  KC_HTTPS_PROTOCOLS: "TLSv1.2,TLSv1.3"
  KC_HTTPS_CIPHER_SUITES: "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"

  # Feature Configuration
  KC_FEATURES: "token-exchange,admin-fine-grained-authz,declarative-user-profile,scripts,upload-scripts,web-authn,client-policies,dynamic-scopes"
  
  # Caching Configuration
  KC_CACHE: "ispn"
  KC_CACHE_STACK: "kubernetes"
  KC_CACHE_CONFIG_FILE: "cache-ispn-kubernetes.xml"
  
  # Transaction Settings
  KC_TRANSACTION_XA_ENABLED: "true"
  
  # Logging and Monitoring
  KC_LOG_LEVEL: "INFO"
  KC_SPI_EVENTS_LISTENER: "jboss-logging,metrics-listener"
  
  # Admin Credentials
  KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN_USER}"
  KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
  
  # JVM Settings
  JAVA_OPTS_APPEND: "-Xms2048m -Xmx4096m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:InitiatingHeapOccupancyPercent=70 -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"