apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: agricultural-system
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: autonomous-agricultural-management
    app.kubernetes.io/component: identity-provider
  annotations:
    security.kubernetes.io/seccomp-profile: runtime/default
    container.security.io/pod-security: restricted
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: keycloak
      annotations:
        checksum/config: "${CONFIG_CHECKSUM}"
        security.alpha.kubernetes.io/sysctls: "net.ipv4.tcp_keepalive_time=60,net.ipv4.tcp_keepalive_intvl=15,net.ipv4.tcp_keepalive_probes=6"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.1.1
        imagePullPolicy: IfNotPresent
        args: ["start"]
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        envFrom:
        - configMapRef:
            name: keycloak-config
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /opt/keycloak/data
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - keycloak
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      serviceAccountName: keycloak