apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: agricultural-system
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: autonomous-agricultural-management
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/managed-by: kustomize
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/local-storage
    volume.kubernetes.io/storage-class: standard-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-storage
  resources:
    requests:
      storage: 500Gi
  volumeMode: Filesystem