apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: agricultural-system
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: autonomous-agricultural-management
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/managed-by: kustomize
  annotations:
    service.beta.kubernetes.io/description: "MinIO distributed object storage service for agricultural data"
    service.beta.kubernetes.io/version: "RELEASE.2023-07-07"
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      protocol: TCP
      appProtocol: http
    - name: console
      port: 9001
      targetPort: 9001
      protocol: TCP
      appProtocol: http
  selector:
    app.kubernetes.io/name: minio
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  publishNotReadyAddresses: false
  ipFamilyPolicy: PreferDualStack
  internalTrafficPolicy: Cluster