apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: agricultural-system
  labels:
    app: prometheus
    component: monitoring
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: autonomous-agricultural-management
    app.kubernetes.io/component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s
      external_labels:
        environment: production
        cluster: agricultural-system

    rule_files:
      - "/etc/prometheus/rules/*.rules"

    scrape_configs:
      # DeepStream video analytics monitoring
      - job_name: 'deepstream'
        metrics_path: '/metrics'
        scheme: http
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['agricultural-system']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: deepstream
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: keep
            regex: \d+
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+);(.+)
            replacement: $1:$2
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'deepstream_video_processing_latency_.*'
            action: keep

      # ROS 2 robotics monitoring
      - job_name: 'ros2'
        metrics_path: '/metrics'
        scheme: http
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['agricultural-system']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: ros2
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: keep
            regex: \d+
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+);(.+)
            replacement: $1:$2

      # TAO ML model monitoring
      - job_name: 'tao'
        metrics_path: '/metrics'
        scheme: http
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['agricultural-system']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: tao
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: keep
            regex: \d+
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+);(.+)
            replacement: $1:$2
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'tao_model_inference_.*'
            action: keep

      # Gazebo simulation monitoring
      - job_name: 'gazebo'
        metrics_path: '/metrics'
        scheme: http
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['agricultural-system']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: gazebo
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: keep
            regex: \d+
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+);(.+)
            replacement: $1:$2

      # Node exporter for hardware metrics
      - job_name: 'node'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']
          scheme: http
          timeout: 10s
          api_version: v2